export enum Code {
    CADASTRADO_COM_SUCESSO = 1,
    USUARIO_NAO_ENCONTRADO = 2,
    USUARIO_EXISTENTE = 3,
    USUARIO_EXISTENTE_SEM_LOGON_GOOGLE = 5,
    USUARIO_EXISTENTE_COM_LOGON_GOOGLE = 6,
    SENHA_INCORRETA = 7,
    NAO_MAPEADO = 4
}